name: Release And Upload
on:
  release:
    types:
      - published
jobs:
  build-and-upload:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup pNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies for Tauri (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
      - name: Load cached node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-
      - name: Install dependencies
        run: pnpm install
      - name: Build the app
        run: pnpm tauri build
      - name: (.dmg) Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file_glob: true
          file: src-tauri/target/debug/bundle/*/*.dmg
      - name: (.msi) Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file_glob: true
          file: src-tauri/target/debug/bundle/*/*.msi
      - name: (.deb) Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file_glob: true
          file: src-tauri/target/debug/bundle/*/*.deb
      - name: (.AppImage) Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file_glob: true
          file: src-tauri/target/debug/bundle/*/*.AppImage
      - name: (.app) Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file_glob: true
          file: src-tauri/target/debug/bundle/*/*.app
